"""add_avatars

Revision ID: 249f728c6e16
Revises: 7fc4b4fe8497
Create Date: 2024-03-05 21:23:02.313164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249f728c6e16'
down_revision = '7fc4b4fe8497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
